spring:
  application:
    name: shop-api
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: sys as sysdba
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

services:
  mail-api:
    url: http://localhost:8090/mail
